// flow-typed signature: 7a3e6969d43c2b61e29a72d69ff870e1
// flow-typed version: <<STUB>>/uid_v^0.0.2/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uid/index' {
  declare module.exports: $Exports<'uid'>;
}
declare module 'uid/index.js' {
  declare module.exports: $Exports<'uid'>;
}
